M48
; DRILL file KiCad 10.0.1 date 2026-06-23T19:27:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-23T19:27:45+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X90.846Y-39.114
X97.96Y-37.19
T2
X90.77Y-44.33
X93.31Y-44.33
X95.85Y-44.33
M30
